# filepath: .github/workflows/daily_crawler.yml

name: Daily VnExpress Crawler

on:
  workflow_dispatch: # Cho phép chạy thủ công từ tab Actions trên GitHub
  schedule:
    # Chạy vào 23:30 mỗi ngày (giờ Việt Nam)
    # 16:30 UTC tương đương 23:30 giờ Việt Nam (UTC+7)
    - cron: '30 16 * * *'

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11' # Sử dụng phiên bản Python ổn định

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # NÂNG CẤP: Thêm playwright và playwright-stealth
        pip install requests beautifulsoup4 fpdf2 pillow google-api-python-client google-auth-httplib2 google-auth-oauthlib pytz python-dotenv playwright playwright-stealth

    - name: Install Playwright browsers
      # BƯỚC QUAN TRỌNG: Phải cài đặt trình duyệt cho Playwright
      run: playwright install --with-deps

    - name: Run the crawler script
      env:
        # Sử dụng các secrets đã tạo
        GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        # NÂNG CẤP: Truyền danh sách mục tiêu vào script
        CRAWL_TARGETS: ${{ secrets.CRAWL_TARGETS }}
      run: python main.py